CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(50) NOT NULL
);

CREATE TABLE tasks (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(255) NOT NULL,
                       description VARCHAR(255),
                       priority VARCHAR(50) NOT NULL,
                       status VARCHAR(50) NOT NULL DEFAULT 'NEW',
                       owner_id BIGINT,
                       CONSTRAINT fk_tasks_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE audit_logs (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            action VARCHAR(255) NOT NULL,
                            task_id BIGINT,
                            details VARCHAR(500),
                            created_at TIMESTAMP NOT NULL
);

CREATE TABLE tags (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE task_tags (
                           task_id BIGINT NOT NULL,
                           tag_id BIGINT NOT NULL,
                           PRIMARY KEY (task_id, tag_id),
                           CONSTRAINT fk_task_tags_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
                           CONSTRAINT fk_task_tags_tag FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);

INSERT INTO tasks (title, description, priority, status)
VALUES ('Изучить Flyway', 'Первая миграция', 'HIGH', 'NEW'),
       ('Написать тесты', 'Потом', 'MEDIUM', 'NEW');

INSERT INTO tags (name) VALUES ('работа'), ('дом'), ('срочно'), ('учёба');