CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(50) NOT NULL
);

CREATE TABLE tasks (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(255) NOT NULL,
                       description VARCHAR(255),
                       priority VARCHAR(50) NOT NULL,
                       status VARCHAR(50) NOT NULL DEFAULT 'NEW',
                       owner_id BIGINT,
                       CONSTRAINT fk_tasks_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE audit_logs (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            action VARCHAR(255) NOT NULL,
                            task_id BIGINT,
                            created_at TIMESTAMP NOT NULL
);

INSERT INTO tasks (title, description, priority, status)
VALUES ('Изучить Flyway', 'Первая миграция', 'HIGH', 'NEW'),
       ('Написать тесты', 'Потом', 'MEDIUM', 'NEW');