CREATE TABLE refresh_tokens (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                token VARCHAR(255) NOT NULL UNIQUE,
                                user_id BIGINT,
                                expires_at TIMESTAMP NOT NULL,
                                CONSTRAINT fk_refresh_user FOREIGN KEY (user_id) REFERENCES users(id)
);